//THIS FILE IS GENERATED BY STRUCTPROTO, DO NOT EDIT IT!!!
//GENERATE TIME :  2017-03-31 16:46:12.5317837 +0800 CST
#pragma once

#include <string>
#include <vector>
using namespace std;

enum ePlayerState {
	offline  =  0 ,
	online  =  1 ,
	inteam  =  2 ,
	ingame  =  3 ,
};

struct c2s_login {
	int32_t   userid ;
	int serialize(void* buff, int len) const;
	void deserialize(void* buff, int len);
};

struct c2s_enter_room {
	int32_t   userid ;
	int32_t   roomtype ;
	int serialize(void* buff, int len) const;
	void deserialize(void* buff, int len);
};

struct c2s_get_player_info {
	int serialize(void* buff, int len) const;
	void deserialize(void* buff, int len);
};

struct s2c_player_info {
	int32_t   playerid ;
	string   playername ;
	ePlayerState   playerstate ;
	int serialize(void* buff, int len) const;
	void deserialize(void* buff, int len);
};

struct s2c_all_player_info {
	vector<s2c_player_info>   infos ;
	int serialize(void* buff, int len) const;
	void deserialize(void* buff, int len);
};

struct msg_stone {
	int32_t   keyid ;
	int32_t   stoneid ;
	int serialize(void* buff, int len) const;
	void deserialize(void* buff, int len);
};

struct s2c_refresh_stone {
	vector<msg_stone>   stones ;
	int serialize(void* buff, int len) const;
	void deserialize(void* buff, int len);
};

