//THIS FILE IS GENERATED BY STRUCTPROTO, DO NOT EDIT IT!!!
//GENERATE TIME :  2017-03-31 16:46:12.547826 +0800 CST
using System; 
using System.Collections.Generic;
using StructProtocol;


namespace  c2s {
	enum ePlayerState {
		ingame  =  3 ,
		offline  =  0 ,
		online  =  1 ,
		inteam  =  2 ,
	}

	class c2s_login: IStruct {
		public  int   userid ;
		public int serialize(byte[] buff) {
			BuffBuilder bb = new BuffBuilder(buff);
			ushort _member_count =  1 ;
			bb.PushUInt16(_member_count);
			ushort _member_code = 0;
			byte _member_type=0;
			_member_code =  1 ;
			bb.PushUInt16(_member_code);
			_member_type =  4 ;
			bb.PushUInt8(_member_type);
			bb.PushInt32(userid);
			return bb.Size();
		}

		public void deserialize(byte[] buff){
			BuffParser bp = new BuffParser(buff);
			ushort _member_count = bp.PopUInt16();
			ushort _member_code = 0;
			byte _member_type = 0;
			for(var i=0;i<_member_count;i++)
			{
				_member_code = bp.PopUInt16();
				_member_type = bp.PopUInt8();
				switch(_member_code){
					case  1 :
					userid = bp.PopInt32();break;
					default:
					bp.SkipType((eMemberType)_member_type);break;
				}
			}
		}

	}

	class c2s_enter_room: IStruct {
		public  int   userid ;
		public  int   roomtype ;
		public int serialize(byte[] buff) {
			BuffBuilder bb = new BuffBuilder(buff);
			ushort _member_count =  2 ;
			bb.PushUInt16(_member_count);
			ushort _member_code = 0;
			byte _member_type=0;
			_member_code =  1 ;
			bb.PushUInt16(_member_code);
			_member_type =  4 ;
			bb.PushUInt8(_member_type);
			bb.PushInt32(userid);
			_member_code =  2 ;
			bb.PushUInt16(_member_code);
			_member_type =  4 ;
			bb.PushUInt8(_member_type);
			bb.PushInt32(roomtype);
			return bb.Size();
		}

		public void deserialize(byte[] buff){
			BuffParser bp = new BuffParser(buff);
			ushort _member_count = bp.PopUInt16();
			ushort _member_code = 0;
			byte _member_type = 0;
			for(var i=0;i<_member_count;i++)
			{
				_member_code = bp.PopUInt16();
				_member_type = bp.PopUInt8();
				switch(_member_code){
					case  1 :
					userid = bp.PopInt32();break;
					case  2 :
					roomtype = bp.PopInt32();break;
					default:
					bp.SkipType((eMemberType)_member_type);break;
				}
			}
		}

	}

	class c2s_get_player_info: IStruct {
		public int serialize(byte[] buff) {
			BuffBuilder bb = new BuffBuilder(buff);
			ushort _member_count =  0 ;
			bb.PushUInt16(_member_count);
			ushort _member_code = 0;
			byte _member_type=0;
			return bb.Size();
		}

		public void deserialize(byte[] buff){
			BuffParser bp = new BuffParser(buff);
			ushort _member_count = bp.PopUInt16();
			ushort _member_code = 0;
			byte _member_type = 0;
			for(var i=0;i<_member_count;i++)
			{
				_member_code = bp.PopUInt16();
				_member_type = bp.PopUInt8();
				switch(_member_code){
					default:
					bp.SkipType((eMemberType)_member_type);break;
				}
			}
		}

	}

	class s2c_player_info: IStruct {
		public  int   playerid ;
		public  string   playername ;
		public  ePlayerState   playerstate ;
		public int serialize(byte[] buff) {
			BuffBuilder bb = new BuffBuilder(buff);
			ushort _member_count =  3 ;
			bb.PushUInt16(_member_count);
			ushort _member_code = 0;
			byte _member_type=0;
			_member_code =  3 ;
			bb.PushUInt16(_member_code);
			_member_type =  10 ;
			bb.PushUInt8(_member_type);
			bb.PushInt32((int)playerstate);
			_member_code =  1 ;
			bb.PushUInt16(_member_code);
			_member_type =  4 ;
			bb.PushUInt8(_member_type);
			bb.PushInt32(playerid);
			_member_code =  2 ;
			bb.PushUInt16(_member_code);
			_member_type =  11 ;
			bb.PushUInt8(_member_type);
			bb.PushString(playername);
			return bb.Size();
		}

		public void deserialize(byte[] buff){
			BuffParser bp = new BuffParser(buff);
			ushort _member_count = bp.PopUInt16();
			ushort _member_code = 0;
			byte _member_type = 0;
			for(var i=0;i<_member_count;i++)
			{
				_member_code = bp.PopUInt16();
				_member_type = bp.PopUInt8();
				switch(_member_code){
					case  1 :
					playerid = bp.PopInt32();break;
					case  2 :
					playername = bp.PopString();break;
					case  3 :
					playerstate = ( ePlayerState )bp.PopInt32();break;
					default:
					bp.SkipType((eMemberType)_member_type);break;
				}
			}
		}

	}

	class s2c_all_player_info: IStruct {
		public  List<s2c_player_info>   infos = new  List<s2c_player_info> ();
		public int serialize(byte[] buff) {
			BuffBuilder bb = new BuffBuilder(buff);
			ushort _member_count =  1 ;
			bb.PushUInt16(_member_count);
			ushort _member_code = 0;
			byte _member_type=0;
			_member_code =  1 ;
			bb.PushUInt16(_member_code);
			_member_type =  24 ;
			bb.PushUInt8(_member_type);
			bb.PushUInt16((ushort) infos .Count);
			for(int n=0; n <  infos .Count; n++){
				byte[] _buf = new byte[4096];
				ushort elemlen = (ushort) infos [n].serialize(_buf);
				bb.PushUInt16(elemlen);
				bb.PushRangeBuff(_buf,elemlen);
			}

			return bb.Size();
		}

		public void deserialize(byte[] buff){
			BuffParser bp = new BuffParser(buff);
			ushort _member_count = bp.PopUInt16();
			ushort _member_code = 0;
			byte _member_type = 0;
			for(var i=0;i<_member_count;i++)
			{
				_member_code = bp.PopUInt16();
				_member_type = bp.PopUInt8();
				switch(_member_code){
					case  1 :
					{
						ushort arraylen = bp.PopUInt16();
						for (;arraylen>0;arraylen--){
							ushort elemlen = bp.PopUInt16();
							byte[] _buf = bp.PopBytes(elemlen);
							s2c_player_info element = new  s2c_player_info ();
							element.deserialize(_buf);
							infos.Add(element);
						}
					}
					break;
					default:
					bp.SkipType((eMemberType)_member_type);break;
				}
			}
		}

	}

	class msg_stone: IStruct {
		public  int   keyid ;
		public  int   stoneid ;
		public int serialize(byte[] buff) {
			BuffBuilder bb = new BuffBuilder(buff);
			ushort _member_count =  2 ;
			bb.PushUInt16(_member_count);
			ushort _member_code = 0;
			byte _member_type=0;
			_member_code =  2 ;
			bb.PushUInt16(_member_code);
			_member_type =  4 ;
			bb.PushUInt8(_member_type);
			bb.PushInt32(stoneid);
			_member_code =  1 ;
			bb.PushUInt16(_member_code);
			_member_type =  4 ;
			bb.PushUInt8(_member_type);
			bb.PushInt32(keyid);
			return bb.Size();
		}

		public void deserialize(byte[] buff){
			BuffParser bp = new BuffParser(buff);
			ushort _member_count = bp.PopUInt16();
			ushort _member_code = 0;
			byte _member_type = 0;
			for(var i=0;i<_member_count;i++)
			{
				_member_code = bp.PopUInt16();
				_member_type = bp.PopUInt8();
				switch(_member_code){
					case  1 :
					keyid = bp.PopInt32();break;
					case  2 :
					stoneid = bp.PopInt32();break;
					default:
					bp.SkipType((eMemberType)_member_type);break;
				}
			}
		}

	}

	class s2c_refresh_stone: IStruct {
		public  List<msg_stone>   stones = new  List<msg_stone> ();
		public int serialize(byte[] buff) {
			BuffBuilder bb = new BuffBuilder(buff);
			ushort _member_count =  1 ;
			bb.PushUInt16(_member_count);
			ushort _member_code = 0;
			byte _member_type=0;
			_member_code =  1 ;
			bb.PushUInt16(_member_code);
			_member_type =  24 ;
			bb.PushUInt8(_member_type);
			bb.PushUInt16((ushort) stones .Count);
			for(int n=0; n <  stones .Count; n++){
				byte[] _buf = new byte[4096];
				ushort elemlen = (ushort) stones [n].serialize(_buf);
				bb.PushUInt16(elemlen);
				bb.PushRangeBuff(_buf,elemlen);
			}

			return bb.Size();
		}

		public void deserialize(byte[] buff){
			BuffParser bp = new BuffParser(buff);
			ushort _member_count = bp.PopUInt16();
			ushort _member_code = 0;
			byte _member_type = 0;
			for(var i=0;i<_member_count;i++)
			{
				_member_code = bp.PopUInt16();
				_member_type = bp.PopUInt8();
				switch(_member_code){
					case  1 :
					{
						ushort arraylen = bp.PopUInt16();
						for (;arraylen>0;arraylen--){
							ushort elemlen = bp.PopUInt16();
							byte[] _buf = bp.PopBytes(elemlen);
							msg_stone element = new  msg_stone ();
							element.deserialize(_buf);
							stones.Add(element);
						}
					}
					break;
					default:
					bp.SkipType((eMemberType)_member_type);break;
				}
			}
		}

	}

}
